rework

diff --git a/auto-install b/auto-install
--- a/auto-install
+++ b/auto-install
@@ -1,25 +1,31 @@
 #!/bin/bash
 [ -z $ZSH_VERSION ] && [ -z $BASH_VERSION ] && echo "Unsupported shell, user either bash or zsh" 1>&2 && return 99
 
+[ "$1" == "--curr-dir" ] && { CURR_DIR=true; shift; } || CURR_DIR=false
+
 VER="$1"
 [ "$VER" == "" ] && VER="$ENT_VERSION"
 [ "$VER" == "" ] && echo "please provide the version via paramenter or enviroment var \"ENT_VERSION\"" 1>&2 && exit 1
 
-[ -d "$HOME/.entando/ent/$VER" ] && echo "Destination dir \"$HOME/.entando/ent/$VER\" already exists, remove it an try again if you want to reinstall it" 1>&2 && exit 1
+$CURR_DIR || cd "$HOME"
+
+TGT_DIR="$PWD"
+PREFIX='.entando/ent'
+
+[ -d "$PREFIX/$VER" ] && echo "Destination dir \"$TGT_DIR/$PREFIX/$VER\" already exists, remove it an try again if you want to reinstall it" 1>&2 && exit 1
 
 git --version
-[ $? -ne 0 ] && echo "please install git" 1>&2 && exit 99
-
-cd "$HOME"
+[ $? -ne 0 ] && echo "please install git" 1>&2 && exit 91
 
 set -e
 
-mkdir -p ".entando/ent"
-cd ".entando/ent"
+mkdir -p "$PREFIX"
+cd "$PREFIX"
 
 git clone https://github.com/w-caffiero-entando/e3e62dc4.git "$VER"
 cd "$VER"
 git checkout -b "$VER" origin/"$VER" 1>/dev/null
+[ $? -ne 0 ] && echo "unable to checkout the provided version \"$VER\"" 1>&2 && exit 92
 
 echo "."
 echo ".."
@@ -28,7 +34,7 @@ echo "ENT INSTALLED."
 echo ""
 echo "Activate using command:"
 echo ""
-echo -e "\tsource $HOME/.entando/ent/$VER/activate"
+echo -e "\tsource $TGT_DIR/$PREFIX/$VER/activate"
 echo ""
 echo "Then get help using this command:"
 echo ""
