UUUUUUUUUUUUUUUU

diff --git a/auto-install b/auto-install
--- a/auto-install
+++ b/auto-install
@@ -1,18 +1,20 @@
 #!/bin/bash
 [ -z $ZSH_VERSION ] && [ -z $BASH_VERSION ] && echo "Unsupported shell, user either bash or zsh" 1>&2 && return 99
 
-[ "$1" == "--curr-dir" ] && { CURR_DIR=true; shift; } || CURR_DIR=false
+[ "$1" == "--curr-dir" ] && {
+  CURR_DIR=true
+  shift
+} || CURR_DIR=false
 
-VER="$1"
-[ "$VER" == "" ] && VER="$ENT_VERSION"
-[ "$VER" == "" ] && echo "please provide the version via paramenter or enviroment var \"ENT_VERSION\"" 1>&2 && exit 1
+REL="$1"
+shift
+[ "$REL" == "" ] && REL="$ENTANDO_RELEASE"
+[ "$REL" == "" ] && REL="v6.2.0" && echo "Assuming ENTANDO_RELEASE=\"$REL\""
 
 $CURR_DIR || cd "$HOME"
 
 TGT_DIR="$PWD"
 PREFIX='.entando/ent'
-
-[ -d "$PREFIX/$VER" ] && echo "Destination dir \"$TGT_DIR/$PREFIX/$VER\" already exists, remove it an try again if you want to reinstall it" 1>&2 && exit 1
 
 git --version
 [ $? -ne 0 ] && echo "please install git" 1>&2 && exit 91
@@ -22,10 +24,39 @@ set -e
 mkdir -p "$PREFIX"
 cd "$PREFIX"
 
-git clone https://github.com/w-caffiero-entando/e3e62dc4.git "$VER"
-cd "$VER"
-git checkout -b "$VER" origin/"$VER" 1>/dev/null
-[ $? -ne 0 ] && echo "unable to checkout the provided version \"$VER\"" 1>&2 && exit 92
+clone() {
+  local URL="$1"; local TAG="$2"; local FLD="$3"; local DSC="$4"
+  if [[ ! -d "$FLD" ]]; then
+    git clone "$URL" "$FLD"
+    if cd "$FLD"; then
+      (
+        git fetch --tags
+        if ! git checkout -b "$TAG" "$TAG" 1> /dev/null; then
+          echo "Unable to checkout the provided $DSC \"$TAG\"" 1>&2
+          exit 92
+        fi
+      )
+      if [ $? ]; then
+        cd -
+      else
+        cd -
+        rm -rf "./$FLD"
+        exit "$?"
+      fi
+    fi
+  else
+    echo "Destination dir \"$PWD/$FLD\" already exists and will not be overwritten.." 1>&2
+  fi
+}
+
+clone "https://github.com/entando/entando-releases.git" "$REL" "$REL" "release"
+[[ -z "$ENTANDO_CLI_VERSION" ]] && source "./$REL/dist/manifest"
+[[ -z "$ENTANDO_CLI_VERSION" ]] && echo "Unable to determine the proper entando cli version, please provide it via environment variable \"ENTANDO_CLI_VERSION\"" 1>&2 && exit 1
+cd "$REL"
+mkdir -p "./cli"
+clone "https://github.com/w-caffiero-entando/e3e62dc4.git" "$ENTANDO_CLI_VERSION" "cli/$ENTANDO_CLI_VERSION" "version"
+cd "cli/$ENTANDO_CLI_VERSION"
+ln -sf "../dist" ./
 
 echo "."
 echo ".."
@@ -34,11 +65,9 @@ echo "ENT INSTALLED."
 echo ""
 echo "Activate using command:"
 echo ""
-echo -e "\tsource $TGT_DIR/$PREFIX/$VER/activate"
+echo -e "\tsource $TGT_DIR/$PREFIX/$REL/cli/$ENTANDO_CLI_VERSION/activate"
 echo ""
-echo "Then get help using this command:"
-echo ""
-echo -e "\tent-help.sh"
+echo -e "and then get help using this command: ent-help.sh"
 echo ""
 echo "============================================================"
 echo ".."
diff --git a/bin/ent-prj b/bin/ent-prj
--- a/bin/ent-prj
+++ b/bin/ent-prj
@@ -9,6 +9,88 @@ cd "$DIR/.." || {
 cd - > /dev/null || FATAL "internal error"
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+publish_version() {
+  push_git "$@"
+  push_docker "$@"
+}
+
+push_docker() {
+  [ -z "$DOCKER_REGISTRY_URL" ] &&  _log_d 1 "No docker registry configured, using default"
+  docker login "$DOCKER_REGISTRY_URL"
+  docker push
+}
+
+push_git() {
+  ensure_valid_location
+
+  [ "$1" == "--force" ] && {
+    shift
+    FORCE=true
+  } || FORCE=false
+
+  set_or_ask "VERSION_NUMBER" "$1" "%sp %var" "" "assert_fdn"
+  set_or_ask "VERSION_COMMENT" "$2" "%sp %var" "$VERSION_NUMBER  - $(date -u '+%Y-%m-%dT%H:%M:%S%z')" "assert_nn"
+
+  cd bundle > /dev/null || FATAL "internal error"
+
+  if [ ! "$(git status --porcelain)" ]; then
+    ask "No change detected; Should I proceed anyway?" || EXIT_UE "User interrupted"
+  else
+    git add -A
+    git commit -m "$VERSION_COMMENT"
+  fi
+
+  git fetch --tags 1> /dev/null
+
+  if git tag | grep -q -F "$VERSION_NUMBER"; then
+    if $FORCE; then
+      git tag -d "$VERSION_NUMBER" 2> /dev/null 1>&2
+    else
+      FATAL "Version \"$VERSION_NUMBER\" already exists"
+    fi
+  fi
+
+  git tag "$VERSION_NUMBER"
+
+  if $FORCE; then
+    RES="$(git push --force 2>&1)"
+    RV=$?
+  else
+    RES="$(git push 2>&1)"
+    RV=$?
+  fi
+
+  if [ $RV -ne 0 ]; then
+    if echo "$RES" | head -n 2 | grep -q -F '! [rejected]'; then
+      _log_w 1 "Unable to push to the remote repository, reason; REMOTE HISTORY NOT COMPATIBLE"
+      _log_w 1 "I'll try to fix it"
+
+      git fetch origin master \
+        && git rebase -Xtheirs origin/master
+
+      RES="$(git push 2>&1)"
+      RV=$?
+    fi
+  fi
+
+  if [ $RV -ne 0 ]; then
+    _log_e 1 "Unable to push to the remote repository, reason; $RES"
+    FATAL "Manual intervention required"
+  else
+    if echo "$RES" | head -n 2 | grep -q -F 'up-to-date'; then
+      _log_w 1 "Nothing was published: The remote repository is already up to date"
+    else
+      _log_i 1 "Version $VERSION_NUMBER published"
+    fi
+  fi
+
+  git push --tags --force 2> /dev/null
+  RV=$?
+  if [ $RV -ne 0 ]; then
+    _log_e 1 "Error pushing the version tag"
+  fi
+}
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 init_project() {
   _log_i 1 "Preparing.."
   npm link generator-jhipster-entando
@@ -99,7 +181,7 @@ init_pub() {
   initialize_publication_repository
   ensure_valid_location :initialized
 
-  _log_i 1 "bundle package repository initialized"
+  _log_i 1 "bundle publication repository initialized"
 }
 
 initialize_publication_repository() {
@@ -141,28 +223,22 @@ RUN() {
     case "$cmd" in
       "init") #H: initializes the project
         init_project
-        index_of_arg "--AND" "$@" || shift $?
         ;;
-
       "gen") #H: initializes the project
         generate_project "$@"
-        index_of_arg "--AND" "$@" || shift $?
         ;;
-
       "init-pub") #H: initializes the publication
         init_pub "$@"
-        index_of_arg "--AND" "$@" || shift $?
         ;;
-      "bump") #H: bumps a new version given the VERSION_NUMBER
-        set_nn_fdn "VERSION_NUMBER" "${1-}"
-        repo_bump
-        index_of_arg "--AND" "$@" || shift $?
+      "publish-version") #H: bumps a new version given the VERSION_NUMBER
+        publish_version "$@"
         ;;
       *)
-        H
+        H; break
         ;;
     esac
     [ -z "$1" ] && break
+    index_of_arg "--AND" "$@" || shift $?
   done
 }
 
@@ -172,7 +248,7 @@ generate_ent_project_file() {
   #  }
 
   [ -f ".ent-prj" ] && return 0
-  echo "# ENT-PRJ / $(date '+%Y-%m-%dT%H:%M:%S%z')" > ".ent-prj"
+  echo "# ENT-PRJ / $(date -u '+%Y-%m-%dT%H:%M:%S%z')" > ".ent-prj"
 }
 
 ensure_valid_location() {
@@ -189,6 +265,8 @@ ensure_valid_location() {
     cd bundle || FATAL "internal error"
 
     # git initialized
+    [ -d ".git" ] || FATAL "Publication repository is not initialized"
+
     ORIG=$(git remote get-url origin 2> /dev/null)
     [ -z "$ORIG" ] && FATAL "Repo not initialized (run \"${0##*/} init ...\")"
 
@@ -199,15 +277,20 @@ ensure_valid_location() {
     # git master branch
     if [ "$(git ls-remote origin master)" ]; then
       _log_w 1 "A remote master has been detected"
-      ask "Do you want to import it?" && {
-        (
-          _log_w 1 "Saving your change to a backup branch"
-          git checkout -b "==AUTOSAVE=$(date '+%Y-%m-%dT%H:%M:%S%z')=="
-          git add -A && git commit -m "==AUTOSAVE=$(date '+%Y-%m-%dT%H:%M:%S%z')=="
-        ) && 2> /dev/nulll
-        git fetch origin master
-        git checkout -b master
-      }
+      ask "Do you want to import it?" || FATAL "Unable to proceed; manual intervention required"
+
+      if [ "$(git status --porcelain)" ]; then
+        local BBN="__AUTOSAVE_$(date -u '+%Y-%m-%dT%H-%M-%S%z')__"
+        _log_w 1 "Saving the local changes to the backup branch: \"$BBN\""
+        git reset HEAD 2> /dev/null
+        git checkout -b "$BBN" \
+          && git add -A \
+          && git commit -m "$BBN"
+      fi
+
+      _log_d 1 "Checking out the remote master"
+      git fetch origin master
+      git checkout -b master origin/master
     else
       echo "" > .gitignore
       git add -A
